# Generated by Django 2.1.5 on 2021-07-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210705_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
