# Generated by Django 3.2.6 on 2022-01-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('bio', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='project', max_length=100, null=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('technology', models.TextField(max_length=50, null=True)),
                ('status', models.CharField(default='done', max_length=20, null=True)),
                ('source', models.TextField(default='link', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='uploads')),
                ('skill_name', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
