# Generated by Django 3.2.6 on 2022-01-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name',
        ),
    ]
